Repository norkator/paketin-seuranta, pull requests merged in 2020-08, with the labels that each got.

#22 Jenkinsfile from example for testing and setup
  .gitignore
  Jenkinsfile
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: enhancement

#21 Feature/bring tracking implementation
  README.md
  app/src/main/java/com/nitramite/courier/BringStrategy.java
  app/src/main/java/com/nitramite/paketinseuranta/CarrierDetectorTask.java
  app/src/main/java/com/nitramite/paketinseuranta/FragmentTrackedDelivery.java
  app/src/main/java/com/nitramite/paketinseuranta/Parcel.java
  app/src/main/java/com/nitramite/paketinseuranta/updater/UpdaterLogic.java
  app/src/main/java/com/nitramite/utils/CarrierUtils.java
  app/src/main/res/mipmap-hdpi/bring_logo.png
  app/src/main/res/mipmap-mdpi/bring_logo.png
  app/src/main/res/mipmap-xhdpi/bring_logo.png
  app/src/main/res/mipmap-xxhdpi/bring_logo.png
  app/src/main/res/mipmap-xxxhdpi/bring_logo.png
Labels: enhancement

#23 4PX strategy and other fixes
  app/build.gradle
  app/src/main/java/com/nitramite/adapters/CustomParcelsAdapterV2.java
  app/src/main/java/com/nitramite/courier/BringStrategy.java
  app/src/main/java/com/nitramite/courier/CainiaoStrategy.java
  app/src/main/java/com/nitramite/courier/FourPXStrategy.java
  app/src/main/java/com/nitramite/courier/fourpx/FourPXEvent.java
  app/src/main/java/com/nitramite/courier/fourpx/FourPXParcel.java
  app/src/main/java/com/nitramite/courier/fourpx/ListTrackResponse.java
  app/src/main/java/com/nitramite/paketinseuranta/Archive.java
  app/src/main/java/com/nitramite/paketinseuranta/CarrierDetectorTask.java
  app/src/main/java/com/nitramite/paketinseuranta/FragmentTrackedDelivery.java
  app/src/main/java/com/nitramite/paketinseuranta/MainMenu.java
  app/src/main/java/com/nitramite/paketinseuranta/MyPreferencesActivity.java
  app/src/main/java/com/nitramite/paketinseuranta/Parcel.java
  app/src/main/java/com/nitramite/paketinseuranta/PhaseNumber.java
  app/src/main/java/com/nitramite/paketinseuranta/updater/UpdaterLogic.java
  app/src/main/java/com/nitramite/utils/CarrierUtils.java
  app/src/main/java/com/nitramite/utils/DateTimeUtils.java
  app/src/main/java/com/nitramite/utils/OkHttpUtils.java
  app/src/main/java/com/nitramite/utils/ThemeUtils.java
  app/src/main/res/drawable/ic_clear_black.xml
  app/src/main/res/drawable/ic_search_black.xml
  app/src/main/res/drawable/ic_waiting4pickup.xml
  app/src/main/res/layout/activity_archive.xml
  app/src/main/res/layout/content_main_menu.xml
  app/src/main/res/mipmap-hdpi/fpx_logo.png
  app/src/main/res/mipmap-mdpi/fpx_logo.png
  app/src/main/res/mipmap-xhdpi/fpx_logo.png
  app/src/main/res/mipmap-xxhdpi/fpx_logo.png
  app/src/main/res/mipmap-xxxhdpi/fpx_logo.png
  app/src/main/res/values-fi-rFI/strings.xml
  app/src/main/res/values/strings.xml
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
Labels: enhancement

#32 Feature/check for hard coded strings
  app/src/main/java/com/nitramite/adapters/CustomAutoCompleteAdapter.java
  app/src/main/java/com/nitramite/adapters/CustomCarrierSpinnerAdapter.java
  app/src/main/java/com/nitramite/adapters/CustomParcelsAdapterV2.java
  app/src/main/java/com/nitramite/courier/ArraPakettiStrategy.java
  app/src/main/java/com/nitramite/courier/BringStrategy.java
  app/src/main/java/com/nitramite/courier/CainiaoStrategy.java
  app/src/main/java/com/nitramite/courier/ChinaPostAirMailStrategy.java
  app/src/main/java/com/nitramite/courier/Constants.java
  app/src/main/java/com/nitramite/courier/Courier.java
  app/src/main/java/com/nitramite/courier/DHLActiveTrackingStrategy.java
  app/src/main/java/com/nitramite/courier/DHLAmazonStrategy.java
  app/src/main/java/com/nitramite/courier/DHLExpressStrategy.java
  app/src/main/java/com/nitramite/courier/FedExStrategy.java
  app/src/main/java/com/nitramite/courier/FourPXStrategy.java
  app/src/main/java/com/nitramite/courier/GlsStrategy.java
  app/src/main/java/com/nitramite/courier/MatkahuoltoStrategy.java
  app/src/main/java/com/nitramite/courier/PostNordStrategy.java
  app/src/main/java/com/nitramite/courier/PostiStrategy.java
  app/src/main/java/com/nitramite/courier/UPSStrategy.java
  app/src/main/java/com/nitramite/courier/USPSStrategy.java
  app/src/main/java/com/nitramite/courier/YanwenStrategy.java
  app/src/main/java/com/nitramite/courier/fourpx/FourPXEvent.java
  app/src/main/java/com/nitramite/courier/fourpx/FourPXParcel.java
  app/src/main/java/com/nitramite/courier/fourpx/ListTrackResponse.java
  app/src/main/java/com/nitramite/paketinseuranta/Archive.java
  app/src/main/java/com/nitramite/paketinseuranta/CarrierDetectorTask.java
  app/src/main/java/com/nitramite/paketinseuranta/Constants.java
  app/src/main/java/com/nitramite/paketinseuranta/CustomZoomLayout.java
  app/src/main/java/com/nitramite/paketinseuranta/DatabaseHelper.java
  app/src/main/java/com/nitramite/paketinseuranta/FragmentNumberList.java
  app/src/main/java/com/nitramite/paketinseuranta/FragmentTrackedDelivery.java
  app/src/main/java/com/nitramite/paketinseuranta/MainMenu.java
  app/src/main/java/com/nitramite/paketinseuranta/MyPreferencesActivity.java
  app/src/main/java/com/nitramite/paketinseuranta/OnSwipeTouchListener.java
  app/src/main/java/com/nitramite/paketinseuranta/Parcel.java
  app/src/main/java/com/nitramite/paketinseuranta/ParcelEditor.java
  app/src/main/java/com/nitramite/paketinseuranta/ParcelService.java
  app/src/main/java/com/nitramite/paketinseuranta/ParcelServiceTimer.java
  app/src/main/java/com/nitramite/paketinseuranta/PhaseNumber.java
  app/src/main/java/com/nitramite/paketinseuranta/Widget.java
  app/src/main/java/com/nitramite/paketinseuranta/notifier/PushService.java
  app/src/main/java/com/nitramite/paketinseuranta/notifier/PushUtils.java
  app/src/main/java/com/nitramite/paketinseuranta/updater/UpdaterLogic.java
  app/src/main/java/com/nitramite/utils/CSVExporter.java
  app/src/main/java/com/nitramite/utils/CarrierUtils.java
  app/src/main/java/com/nitramite/utils/DateTimeUtils.java
  app/src/main/java/com/nitramite/utils/LocaleUtils.java
  app/src/main/java/com/nitramite/utils/OkHttpUtils.java
  app/src/main/java/com/nitramite/utils/ThemeUtils.java
  app/src/main/java/com/nitramite/utils/Utils.java
  app/src/main/res/layout/activity_maps.xml
  app/src/main/res/values-fi-rFI/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, good first issue

#25 Last update label, issue #10 ❔
  app/src/main/java/com/nitramite/adapters/CustomParcelsAdapterV2.java
  app/src/main/java/com/nitramite/paketinseuranta/Archive.java
  app/src/main/java/com/nitramite/paketinseuranta/Constants.java
  app/src/main/java/com/nitramite/paketinseuranta/DatabaseHelper.java
  app/src/main/java/com/nitramite/paketinseuranta/MainMenu.java
  app/src/main/java/com/nitramite/paketinseuranta/Parcel.java
  app/src/main/java/com/nitramite/paketinseuranta/ParcelItem.java
  app/src/main/res/layout/parcel_item.xml
  app/src/main/res/values-fi-rFI/strings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/preferences.xml
Labels: enhancement

#37 Feature/ups strategy improvements
  app/src/main/java/com/nitramite/courier/UPSStrategy.java
Labels: enhancement

#39 Feature/postnord strategy improvements
  app/src/main/java/com/nitramite/courier/PostNordStrategy.java
Labels: enhancement

#35 Bug/fix broken backup feature 😠 🤪
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nitramite/paketinseuranta/BackupManager.java
  app/src/main/java/com/nitramite/paketinseuranta/Constants.java
  app/src/main/java/com/nitramite/paketinseuranta/DatabaseHelper.java
  app/src/main/java/com/nitramite/paketinseuranta/MainMenu.java
  app/src/main/java/com/nitramite/utils/Backup.java
  app/src/main/java/com/nitramite/utils/BackupUtils.java
  app/src/main/java/com/nitramite/utils/DialogUtils.java
  app/src/main/java/com/nitramite/utils/SharedPreferencesUtils.java
  app/src/main/res/layout/activity_backup_manager.xml
  app/src/main/res/layout/database_backup_dialog.xml
  app/src/main/res/values-fi-rFI/strings.xml
  app/src/main/res/values/strings.xml
Labels: bug, help wanted

#44 Feature/in app billing implementation
  app/build.gradle
  app/src/main/java/com/nitramite/paketinseuranta/Constants.java
  app/src/main/java/com/nitramite/paketinseuranta/MainMenu.java
  app/src/main/res/menu/menu_menu.xml
  app/src/main/res/values-fi-rFI/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#45 Refactored phase number class
  app/src/main/java/com/nitramite/courier/FourPXStrategy.java
  app/src/main/java/com/nitramite/courier/ParcelObject.java
  app/src/main/java/com/nitramite/courier/PostNordStrategy.java
  app/src/main/java/com/nitramite/paketinseuranta/PhaseNumber.java
  app/src/main/java/com/nitramite/paketinseuranta/updater/UpdaterLogic.java
Labels: enhancement

#46 Yanwen fixing
  app/src/main/java/com/nitramite/courier/YanwenStrategy.java
Labels: bug, enhancement

#51 Fix manual locale/language set problem, SDK29 / Q+
  app/src/main/java/com/nitramite/paketinseuranta/Archive.java
  app/src/main/java/com/nitramite/paketinseuranta/BackupManager.java
  app/src/main/java/com/nitramite/paketinseuranta/BarcodeList.java
  app/src/main/java/com/nitramite/paketinseuranta/Parcel.java
  app/src/main/java/com/nitramite/paketinseuranta/ParcelEditor.java
  app/src/main/java/com/nitramite/utils/LocaleUtils.java
Labels: bug

#50 Fixing empty insert problem
  app/src/main/java/com/nitramite/courier/ParcelObject.java
  app/src/main/java/com/nitramite/paketinseuranta/DatabaseHelper.java
  app/src/main/java/com/nitramite/paketinseuranta/FragmentNumberList.java
  app/src/main/java/com/nitramite/paketinseuranta/FragmentTrackedDelivery.java
  app/src/main/java/com/nitramite/paketinseuranta/ParcelEditor.java
  app/src/main/java/com/nitramite/paketinseuranta/ParcelItem.java
  app/src/main/java/com/nitramite/paketinseuranta/updater/UpdaterLogic.java
  app/src/main/java/com/nitramite/utils/CarrierUtils.java
  app/src/main/java/com/nitramite/utils/LocaleUtils.java
Labels: bug

#59 Adding tests run possibilities
  Jenkinsfile
  app/build.gradle
  app/src/androidTest/java/com/nitramite/paketinseuranta/ExampleInstrumentedTest.java
  app/src/test/java/android/util/Log.java
  app/src/test/java/com/nitramite/paketinseuranta/UtilsUnitTest.java
Labels: enhancement

#58 Switching to Semver versioning
  README.md
Labels: enhancement

#60 Fix issue with pull down swipe refresh list view scroll
  app/build.gradle
  app/src/main/java/com/nitramite/paketinseuranta/MainMenu.java
Labels: bug
